version: "3.9"
services:
    auto-compound:
        image: oat9002/auto-compound:latest
        restart: always
        env_file:
            - .env
        volumes:
        - "/etc/localtime:/etc/localtime:ro"
        healthcheck:
            test: ["CMD", "sh", "/app/healthcheck.sh"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
