name: docker

on:
    workflow_dispatch:
    workflow_call:
        secrets:
            DOCKERHUB_USERNAME:
                description: "docker username"
                required: true
            DOCKERHUB_TOKEN:
                description: "docker token"
                required: true

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker build and publish
              run: docker buildx build --platform="linux/amd64,linux/arm64,linux/arm/v7" -t oat9002/auto-compound:latest --push .
