name: upload_artifacts

on:
    push:
        tags:
            - "v*"

jobs:
    upload_artifacts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Build Executable files
              run: ./build-executable.sh

            - name: Set GitHub user
              run: |
                  git config --global user.name 'oat9002'
                  git config --global user.email 'oat9002@hotmail.com'

            - name: Publish GitHub Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "auto-compound*"
                  token: ${{ secrets.GITHUB_TOKEN }}
